apiVersion: apps/v1
kind: Deployment
metadata:
  name: polaris-readservice
  labels:
    app: polaris-readservice
spec:
  replicas: 1  # Apenas um pod será criado
  selector:
    matchLabels:
      app: polaris-readservice
  template:
    metadata:
      labels:
        app: polaris-readservice
    spec:
      containers:
        - name: readservice
          image: caiovsk/readservice:latest  # Certifique-se de que a imagem está no Docker Hub
          ports:
            - containerPort: 8081  # Porta exposta no contêiner
          env: 
            - name: DbSettings__ConnectionString
              value: "Data Source=sql-server,1433;Initial Catalog=PolarisContacts;Persist Security Info=True;User ID=sa;Password=YourStrongPassword!;"