apiVersion: v1
kind: Service
metadata:
  name: polaris-readservice
spec:
  selector:
    app: polaris-readservice
  ports:
    - protocol: TCP
      port: 8081       # Porta exposta pelo serviço
      targetPort: 8081 # Porta do contêiner
      nodePort: 30081 # Porta externa
  type: LoadBalancer
